interface/urls.py
#!/usr/bin/env python
#
# urls.py
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
# Author:   Pietro Delsante <pietro.delsante AT gmail.com>
#           The Honeynet Project
#

from django.conf.urls import url
from interface import views

urlpatterns = (
    url(r'^report/(?:(?P<task_id>\d+)/)?$', views.report, name='report'),
    url(r'^group/(?:(?P<group_id>\d+)/)?$', views.group, name='group'),
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^reports/help$', views.reports, name='reports'),
    url(r'^myscans/$', views.my_scans, name='myscans'),
    url(r'^myprofile/$', views.my_profile, name='myprofile'),
    url(r'^creategroup/$', views.new_group, name='creategroup'),
    url(r'^togglebookmark/$', views.star_view, name='star'),

    url(r'^json_tree_graph/(?:(?P<analysis_id>[\w]+)/)?$', views.json_tree_graph, name='json_tree_graph'),
    url(r'^content/(?:(?P<content_id>[\w]+)/)?$', views.content, name='content'),
    url(r'^raw_content/(?:(?P<content_id>[\w]+)/)?$', views.raw_content, name='raw_content'),

    url(r'^$', views.new_task, name='new_task'),
)

rumal/urls.py
#!/usr/bin/env python
#
# urls.py
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
# Author:   Pietro Delsante <pietro.delsante AT gmail.com>
#           The Honeynet Project
#

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from tastypie.api import Api
from interface.api import *

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(CurrentUserResource())
v1_api.register(GroupResource())
v1_api.register(ProxyResource())
v1_api.register(TaskResource())
v1_api.register(AnalysisResource())
v1_api.register(UrlResource())
v1_api.register(BehaviorResource())
v1_api.register(ConnectionResource())
v1_api.register(LocationResource())
v1_api.register(CodeResource())
v1_api.register(SampleResource())
v1_api.register(CertificateResource())
v1_api.register(ExploitResource())
v1_api.register(GraphResource())
v1_api.register(ComboResource())
v1_api.register(CommentResource())
v1_api.register(AdvancedSearchResource())
v1_api.register(GroupScansResource())
v1_api.register(GroupMembersResource())

urlpatterns = (
    # Admin views
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login, name="login"),
    url(r'^logout/$', logout_then_login, name="logout"),

    # APIs
    url(r'^api/', include(v1_api.urls)),

    # Apps
    url(r'', include('interface.urls', namespace="interface", app_name="interface"))
)

interface/forms.py
#!/usr/bin/env python
#
# forms.py
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
# Author:   Pietro Delsante <pietro.delsante AT gmail.com>
#           The Honeynet Project
#

import re
from django import forms
from interface.models import *


class TaskForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        current_user = kwargs.pop('user')
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['sharing_groups'].queryset = current_user.groups.all()

    class Meta:
        model       = Task
        exclude     = ['user', 'submitted_on', 'started_on', 'completed_on', 'status', 'plugin_status']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['user', 'created_on']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'comment-input', 'style': 'width:100%;'}),
        }


class ScanSettingsForm(forms.Form):

    def __init__(self, *args, **kwargs):
        current_user = kwargs.pop('user')
        super(ScanSettingsForm, self).__init__(*args, **kwargs)
        self.fields['sharing_groups'].queryset = current_user.groups.all()

    sharing_model = forms.ChoiceField(choices=SHARING_MODEL_CHOICES)
    sharing_groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), required=False)

class TagForm(forms.Form):
    tags = forms.TextInput()


class NewGroupForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(NewGroupForm, self).__init__(*args, **kwargs)
        self.fields['group_members'].widget.attrs['id'] = 'select_user'
        self.fields['group_name'].widget.attrs['class'] = 'form-control'



    group_name = forms.CharField(required=True)
    group_members = forms.ModelMultipleChoiceField(queryset=User.objects.all())

interface/views.py
#!/usr/bin/env python
#
# views.py
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
# Author:   Pietro Delsante <pietro.delsante AT gmail.com>
#           The Honeynet Project
#
import base64
import hexdump
import magic
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.core.serializers.json import DjangoJSONEncoder
from bson import json_util

from gridfs import GridFS
from pymongo import MongoClient
from bson import ObjectId

from interface.forms import *
from interface.models import *

import requests

from django.core import serializers
from django.core.exceptions import FieldError, ObjectDoesNotExist
import pymongo

client = pymongo.MongoClient()
db = client.thug
tags_db = client.tags

SHARING_MODEL_PUBLIC = 0
SHARING_MODEL_PRIVATE = 1
SHARING_MODEL_GROUPS = 2


@login_required
def new_task(request):
    """
    Create new task for backend to do Thug analysis
    :param request: Contains Scan Information and current logged in user
    :return: Adds task to DB
    """
    context = {
        'active_tab': 'new_task',
        'form': TaskForm(request.POST or None, user=request.user),
    }

    if request.method == 'POST':
        if context['form'].is_valid():
            saved_form = context['form'].save()

            # Assign the current user to the newly created task
            saved_form.user = request.user
            if saved_form.sharing_model == SHARING_MODEL_PRIVATE:
                saved_form.sharing_groups = []
            saved_form.save()

            return HttpResponseRedirect(reverse('interface:myscans'))

    return render(request, 'interface/new_task.html', context)


@login_required
def reports(request):
    """
    Advanced search feature moved to Restful API
    Search help display guide on what operators and fields can be used
    :param request: contains string to parse
    :return: table with scans matching query
    """

    context = {
        'search': None
    }

    context['search'] = request.GET.get('search', '')

    return render(request, 'interface/results.html', context)


@login_required
def my_scans(request):
    tasks = Task.objects
    user_tasks = tasks.filter(user=request.user)
    public_user_tasks = user_tasks.filter(sharing_model__exact=SHARING_MODEL_PUBLIC)
    private_user_tasks = user_tasks.filter(sharing_model__exact=SHARING_MODEL_PRIVATE)
    star_tasks = request.user.star_tasks.all()
    stats = {
        'public': len(public_user_tasks),
        'private': len(private_user_tasks),
        'star': len(star_tasks)
    }
    context = {
        'stats': stats,
    }
    return render(request, 'interface/myscans2.html', context)

@login_required
def my_profile(request):
    """
    Displays Groups of the currently logged in user
    :param request: User
    :return: All groups user is in
    """

    return render(request, 'interface/myprofile.html')

@login_required
def new_group(request):
    """
    Creation of a new group. Group creator is the current logged in User
    :param request: User, group name, group members
    :return:  Creation of group
    """
    context = {
        'form': NewGroupForm(request.POST or None)
    }

    # Create new Group, add group Creator
    if request.method == 'POST':
        if context['form'].is_valid():

            # Google recaptcha validation
            g_recaptcha_response = request.POST['g-recaptcha-response']
            response = recaptcha_validation(g_recaptcha_response)

            if response:

                group_name = request.POST['group_name']
                group = Group.objects.create(name=group_name)

                # add group creator
                GroupCreator.objects.create(group=group, group_creator=request.user)
                group.user_set.add(request.user)
                group.save()
                for i in request.POST.getlist('group_members'):
                     group.user_set.add(User.objects.get(pk=i))

                return HttpResponseRedirect("/myprofile/")

    return render(request, 'interface/newgroup.html', context)

@login_required
def group(request, group_id):
    """
    Loads group page with members, typeahead data for adding members, admin, name, number of scans.
    Retrieving scans and members has been moved to use RESTful API in JS
    Handles modification of group users (only admin can)
    :param request: Current logged in user, Group Info
    :param group_id: unique Id for group
    :return: Group Info, scans and group settings
    """

    group = get_object_or_404(Group, pk=group_id)
    group_creator = GroupCreator.objects.get(group=group).group_creator
    context = {
        'group_id': None,
        'number_of_scans': None,
        'name': None,
        'admin': False,
        'creator': None,
        'user_typeahead': None
    }

    # check for valid group user
    if request.user in group.user_set.all():
        context['group_id'] = group_id
        context['number_of_scans'] = len(Task.objects.filter(sharing_groups=group).values())
        context['name'] = group.name
        context['creator'] = json_util.dumps(group_creator.username)
        context['user_typeahead'] = json_util.dumps([user.username for user in User.objects.all()])

    # User admin has privileges to add/remove users
    if request.user == group_creator:
        context['admin'] = True

    # Modification of Users (add/remove)
    if request.method == 'POST':
        if TagForm(request.POST).is_valid():
            users = request.POST['users'].split(',')
            # Add
            for i in users:
                try:
                    user = User.objects.get(username=i)
                    group.user_set.add(user)
                except ObjectDoesNotExist:  # Catch Invalid user names
                    pass
            # Remove
            for i in group.user_set.all():
                if i == group_creator:
                    continue
                if i.username not in users:
                    group.user_set.remove(i)

            return HttpResponseRedirect("/group/" + group_id + '/')

    return render(request, 'interface/group.html', context)


@login_required
def report(request, task_id):
    """
    Displays Scan results to User. Current Logged in User as the be valid (with in group, public, creator or private)
    Contains comments for selected node.
    Tags for a scan
    Scan owner can change scans sharing model
    :param request: Current logged in user, tags, comments and scan settings
    :param task_id: Unique ID for scan
    :return:
    """
    task = get_object_or_404(Task, pk=task_id)
    context = {
        'task': None,
        'bookmarked': False,
        'authorisation': False,
        'comment_form': CommentForm(request.POST or None),
        'settings_form': ScanSettingsForm(request.POST or None, user=request.user),
        'tags': None,
        'typeahead': 'null'
    }

    if request.method == 'POST':

        # Post comment
        if context['comment_form'].is_valid():

            # Google recaptcha validation
            g_recaptcha_response = request.POST['g-recaptcha-response']
            response = recaptcha_validation(g_recaptcha_response)

            if response:
                # comment authorisation
                if task.sharing_model is SHARING_MODEL_PUBLIC or request.user == task.user or check_group(request, task):
                    save_comment(context, request, task)
            return HttpResponseRedirect("/report/" + task_id+'/')

        elif context['settings_form'].is_valid():
            # Modify settings of scan
            if request.user == task.user:  # only owner can modify
                task.sharing_model = int(context['settings_form'].cleaned_data['sharing_model'])
                task.sharing_groups = context['settings_form'].cleaned_data['sharing_groups']
                if task.sharing_model == SHARING_MODEL_PRIVATE:
                    task.sharing_groups = []
                task.save()
            return HttpResponseRedirect("/report/" + task_id + '/')

        elif TagForm(request.POST).is_valid():  # Add scan tags

            if task.sharing_model is SHARING_MODEL_PUBLIC or request.user == task.user or check_group(request, task):
                create_or_modify_tag(task_id, request.POST['tags'])
            return HttpResponseRedirect("/report/" + task_id + '/')

        else:
            return render(request, 'interface/report.html', context)

    # If scan is public or used is allowed to view scan
    if task.sharing_model is SHARING_MODEL_PUBLIC or request.user == task.user or check_group(request, task) :
        context['task'] = task
        context['authorisation'] = True
        if request.user in task.star.all():
            context['bookmarked'] = True

        # Tag data for scan
        try:
            tags = db.analysiscombo.find_one({'frontend_id': task_id})['tags']
            context['tags'] = ','.join(tags)
        except KeyError:  # No tags exists currently, pass in empty value
            context['tags'] = ''
        except TypeError:  # Mongo error tags is not found
            pass

        # typeahead data
        try:

templates/interface/group.html
{% extends "base.html" %}
{% block title %}Your Scans{% endblock %}
{% block customheaders %}
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.dataTables_themeroller.css">
    <script type="text/javascript" charset="utf8" src="/static/js/jquery.dataTables.min.js"></script>
{#Tags    #}
    <link rel="stylesheet" href="//cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.css" />
    <script src="//cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.min.js"></script>

    <script type="text/javascript" src="/static/js/bootstrap3-typeahead.js"></script>

{% endblock %}
{% block content %}
    <div class="container" style="width:1170px">
        <div class="row">
            <div class="col-md-6" style="margin-bottom:25px;">
                <div class="panel panel-default">
                    <div class="panel-body" style="padding-bottom:0px">
                        <div class="text-center">
                            <h4> Group Info </h4>
                        </div>
                        <table class="table table-striped table-hover" style="font-size:12px;">
                            <tbody>
                                <tr>
                                    <td>Group Name</td>
                                    <td>{{ name }}</td>
                                </tr>
                                <tr>
                                    <td>Admin</td>
                                    <td>{{ creator }}</td>
                                </tr>
                                <tr>
                                    <td>Number of Scans</td>
                                    <td>{{ number_of_scans }}</td>
                                </tr>
                                <tr>
                                    <td>Members</td>
                                    <td id="members">{{ members }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        {% if admin %}

            <div class="col-md-6" style="height:175px;margin-bottom:25px;">
                <div class="panel panel-default">
                    <div class="panel-body" style="padding-bottom:0px">
                        <div class="text-center">
                            <h4> Group User Management </h4>
                        </div>

                        <form id="bootstrapTagsInputForm" method="post" class="form-horizontal">
                                    {% csrf_token %}
                                    <input id="user-input" type="text" name="users" class="form-control"
                                                   value="" data-role="tagsinput" data-provide="typeahead"/>
                                        <input type="submit" id="user_save" class="btn btn-primary" value="Save Users" style="font-size: 10px;"></li>
                        </form>

                    </div>
                </div>
            </div>

        {% endif %}
        </div>
        <div class="row">
                <div id="groupscans" class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Group Scans</h3>
                    </div>
                    <div class="panel-body">

                        <table id="groupscans-table" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>URL</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>URL</th>
                                    <th>Status</th>
                                </tr>
                            </tfoot>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
        </div>
    </div>


{% endblock %}

{% block bottomscripts %}
    var group_id = '{{ group_id| safe }}';
    var admin = '{{ admin | safe }}';
    var creator = {{ creator | safe }};
    var user_typeahead = {{ user_typeahead | safe }};

     $('#user-input').tagsinput({
        typeahead:{
             source: user_typeahead
        }
     });


    $.getJSON("/api/v1/members" + "/?format=json&"+"group="+group_id,
            function(data) {
                for (var i in data.objects){
                    if (admin == 'True'){
                        $('#user-input').tagsinput('add', data.objects[i].username)
                    }
                    $('#members').append(data.objects[i].username + ", ")
                }
            });

    jQuery.fn.dataTableExt.oSort['numeric-html-asc']  = function(a, b) {
        a = parseInt($(a).text());
        b = parseInt($(b).text());
        return ((a < b) ? -1 : ((a > b) ?  1 : 0));
    };

    jQuery.fn.dataTableExt.oSort['numeric-html-desc']  = function(a, b) {
        a = parseInt($(a).text());
        b = parseInt($(b).text());
        return ((a < b) ? 1 : ((a > b) ?  -1 : 0));
    };

    $(document).ready(function() {
        var group_scans_table = $('#groupscans-table').DataTable( {
            "aoColumns" : [
                { "sType" : "numeric-html" },
                null,
                null
            ],
            "columnDefs": [ {
                    "targets": 0,
                    "render": function ( data, type, full, meta ) {
                        return '<a href="/report/'+data+'">'+data+'</a>';
                    }
                }, {
                    "targets": 1,
                    "render": function ( data, type, full, meta ) {
                        return '<p>'+data+'</p>';
                    }
                }, {
                    "targets": 2,
                    "render": function ( data, type, full, meta ) {
                        return '<span class="label label-'+data[1]+'">'+data[0]+'</span>';
                }
            } ]

        });

        $.getJSON("/api/v1/groupscans" + "/?format=json&"+"group="+group_id,
            function(data) {
                for (var i in data.objects) {
                    var id = data.objects[i].id
                    var url = data.objects[i].url
                    var status = data.objects[i].status
                    var label = {};

                    switch (status) {

                        case 0:

                        case 1:
                            label.class = 'info';
                            label.text = 'Pending';
                            break;

                        case 2:
                            label.class = 'danger';
                            label.text = 'Failed';
                            break;

                        case 3:
                            label.class = 'success';
                            label.text = 'Finished';
                            break;

                        case 4:
                            label.class = 'danger';
                            label.text = 'Timeout';
                            break;

                    }

                    group_scans_table.row.add([id, url, [label.text, label.class]]).draw();
                }
        });

    });


{% endblock %}

templates/interface/myprofile.html
{% extends "base.html" %}
{% block title %}Your Scans{% endblock %}
{% block customheaders %}
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.dataTables_themeroller.css">
    <script type="text/javascript" charset="utf8" src="/static/js/jquery.dataTables.min.js"></script>

{% endblock %}
{% block content %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-10">

            <!-- Basic options -->
            <div class="panel panel-primary" id="my_groups">
                <div class="panel-heading">
                    <h3 class="panel-title">My Groups</h3>
                </div>
                <div class="panel-body">

                    <table id="mygroups-table" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Number</th>
                                <th>Name</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Number</th>
                                <th>Name</th>
                            </tr>
                        </tfoot>
                        <tbody id="mygroups-body">
                        </tbody>
                    </table>

                </div>
            </div>

        </div>
        <div class="col-md-2">
            <nav class="bs-docs-sidebar">
                <ul id="sidebar" class="nav nav-stacked fixed">
                    <li>
                        <button id="create-group" class="btn btn-info" onclick="location.href = '/creategroup/';" style="margin-bottom:20px;margin-left:20px;">
                            Create Group
                        </button>
                    </li>
                    <li><a href="#my_groups">My Groups</a></li>
                </ul>
            </nav>
        </div>
    </div>
    </div>


{% endblock %}

{% block bottomscripts %}

    $(document).ready(function() {

        var my_groups_table = $('#mygroups-table').DataTable({
            "columnDefs": [ {
                "targets": 0,
                "render": function ( data, type, full, meta ) {
                    console.log(data);
                    return '<a href="/group/'+data+'">'+data+'</a>';
                }
              } ]
        });

        $.getJSON("/api/v1/current-user" + "/?format=json",
            function(data) {
                groups_url = data.objects[0].groups;
                for (var i in groups_url){

                    $.getJSON(groups_url[i] + "?format=json",
                        function(data) {
                                console.log(data);
                                my_groups_table.row.add([data.id, data.name]).draw();
                    });

                };
        });

    });

{% endblock %}

templates/interface/newgroup.html
{% extends "base.html" %}
{% block title %}Your Scans{% endblock %}
{% block customheaders %}
    {# Google recaptcha for comment security    #}
    <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}
{% block customcss %}
    .panel-heading a:after {
        font-family:'Glyphicons Halflings';
        content:"\e114";
        float: right;
        color: grey;
    }
    .panel-heading a.collapsed:after {
        content:"\e080";
    }

    .fixed {
        position: fixed;
    }

    /* sidebar */
    .bs-docs-sidebar {
        padding-left: 20px;
        margin-top: 0px;
        margin-bottom: 20px;
    }

    /* all links */
    .bs-docs-sidebar .nav>li>a {
        color: #999;
        border-left: 2px solid transparent;
        padding: 4px 20px;
        font-size: 13px;
        font-weight: 400;
    }

    /* nested links */
    .bs-docs-sidebar .nav .nav>li>a {
        padding-top: 1px;
        padding-bottom: 1px;
        padding-left: 30px;
        font-size: 12px;
    }

    /* active & hover links */
    .bs-docs-sidebar .nav>.active>a,
    .bs-docs-sidebar .nav>li>a:hover,
    .bs-docs-sidebar .nav>li>a:focus {
        color: #563d7c;
        text-decoration: none;
        background-color: transparent;
        border-left-color: #563d7c;
    }
    /* all active links */
    .bs-docs-sidebar .nav>.active>a,
    .bs-docs-sidebar .nav>.active:hover>a,
    .bs-docs-sidebar .nav>.active:focus>a {
        font-weight: 700;
    }
    /* nested active links */
    .bs-docs-sidebar .nav .nav>.active>a,
    .bs-docs-sidebar .nav .nav>.active:hover>a,
    .bs-docs-sidebar .nav .nav>.active:focus>a {
        font-weight: 500;
    }

    /* hide inactive nested list */
    .bs-docs-sidebar .nav ul.nav {
        display: none;
    }
    /* show active nested list */
    .bs-docs-sidebar .nav>.active>ul.nav {
        display: block;
    }
    .panel {
        margin: 15px;
    }
{% endblock %}
{% block content %}
    <form method="post">
    {% csrf_token %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
            <!-- Display any form errors -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">Please fill in the form correctly </div>
            {% endif %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{ error|escape }}</div>
            {% endfor %}

            <!-- Basic options -->
            <div class="panel panel-primary" id="thug_base_options">
                <div class="panel-heading">
                    <h3 class="panel-title">Group</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group{% if form.group_name.errors %} has-error{% endif %}">
                        <label for="id_group_name" class="control-label">Group Name:</label>
                        {{ form.group_name }}
                    </div>

                    <div class="form-group{% if form.group_members.errors %} has-error{% endif %}">
                        <label for="id_group_members" class="control-label">Group Members:</label>
                        {{ form.group_members }}
                    </div>

                    <div class="form-group">
                        <div class="g-recaptcha" data-sitekey="6LeFIyYTAAAAAHNC_1fyVKgJGJQP19M2Kcgp_Mrc"></div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-2">
            <nav class="bs-docs-sidebar">
                <ul id="sidebar" class="nav nav-stacked fixed">
                    <li><input type="submit" id="rule_save" class="btn btn-danger" value="Save Group" style="margin-bottom:20px;margin-left:20px;"></li>
                    <li><a href="#thug_base_options">Group</a></li>
                </ul>
            </nav>
        </div>
    </div>
    </div>
</form>


{% endblock %}

{% block bottomscripts %}
    var group_creator = '{{ user }}';


    var select = document.getElementById("select_user");
    for (var i = 0; i < select.length; i++){
        if (group_creator == select.options[i].text) {
            select.options[i].selected = "selected";
        }
    }



{% endblock %}