interface/urls.py
#!/usr/bin/env python
#
# urls.py
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
# Author:   Pietro Delsante <pietro.delsante AT gmail.com>
#           The Honeynet Project
#

from django.conf.urls import url
from interface import views

urlpatterns = (
    url(r'^report/(?:(?P<task_id>\d+)/)?$', views.report, name='report'),
    url(r'^group/(?:(?P<group_id>\d+)/)?$', views.group, name='group'),
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^reports/help$', views.reports, name='reports'),
    url(r'^myscans/$', views.my_scans, name='myscans'),
    url(r'^myprofile/$', views.my_profile, name='myprofile'),
    url(r'^creategroup/$', views.new_group, name='creategroup'),
    url(r'^togglebookmark/$', views.star_view, name='star'),

    url(r'^json_tree_graph/(?:(?P<analysis_id>[\w]+)/)?$', views.json_tree_graph, name='json_tree_graph'),
    url(r'^content/(?:(?P<content_id>[\w]+)/)?$', views.content, name='content'),
    url(r'^raw_content/(?:(?P<content_id>[\w]+)/)?$', views.raw_content, name='raw_content'),

    url(r'^$', views.new_task, name='new_task'),
)

rumal/urls.py
#!/usr/bin/env python
#
# urls.py
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
# Author:   Pietro Delsante <pietro.delsante AT gmail.com>
#           The Honeynet Project
#

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from tastypie.api import Api
from interface.api import *

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(CurrentUserResource())
v1_api.register(GroupResource())
v1_api.register(ProxyResource())
v1_api.register(TaskResource())
v1_api.register(AnalysisResource())
v1_api.register(UrlResource())
v1_api.register(BehaviorResource())
v1_api.register(ConnectionResource())
v1_api.register(LocationResource())
v1_api.register(CodeResource())
v1_api.register(SampleResource())
v1_api.register(CertificateResource())
v1_api.register(ExploitResource())
v1_api.register(GraphResource())
v1_api.register(ComboResource())
v1_api.register(CommentResource())
v1_api.register(AdvancedSearchResource())
v1_api.register(GroupScansResource())
v1_api.register(GroupMembersResource())

urlpatterns = (
    # Admin views
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login, name="login"),
    url(r'^logout/$', logout_then_login, name="logout"),

    # APIs
    url(r'^api/', include(v1_api.urls)),

    # Apps
    url(r'', include('interface.urls', namespace="interface", app_name="interface"))
)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2//static/css/bootstrap.min.css" rel="stylesheet"> -->
    <!-- Include roboto.css to use the Roboto web font, material.css to include the theme and ripples.css to style the ripple effect -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link href="/static/css/roboto.min.css" rel="stylesheet">
    <link href="/static/css/material.min.css" rel="stylesheet">
    <link href="/static/css/ripples.min.css" rel="stylesheet">
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    {% block customheaders %}{% endblock %}
    <style type="text/css">
        html,
        body {
            height: 100%
        }
        #bigwrap {
            height: 100%;
            width: 100%;
        }

        @media (max-width: 767px) {
            body {
                padding-right: 0px;
                padding-left: 0px;
            }
        }
        #searchform {
            width: 370px;
        }

        #searchfield {
            width: 350px;
        }

        {% block customcss %}{% endblock %}
    </style>
</head>

<body>

    <!-- BIG WRAP -->
    <div id="bigwrap">

        <div class="navbar navbar-default" id="topnav">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <i id="submit" class="mdi-action-find-replace mdi-material-black" style="font-size: 36px;padding-top:8px;"></i>
                <form class="navbar-form navbar-left" id="searchform">
                    <input class="form-control col-lg-8" placeholder="Rumal Advanced Search" type="text" id="searchfield">
                </form>
            </div>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="http://thugs-rumal.github.io/advancedsearch.html">Search Help</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">


                    <li class="link"><a href="https://github.com/reachtarunhere/rumal" target="_blank">About</a></li>
                    <li class="link"><a href="/">New Scan</a></li>
                    <li class="dropdown">
                        <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/myscans/">My Scans</a></li>
                            <li><a href="/myprofile/">Profile</a></li>
                            <li><a href="javascript:void(0)">Settings</a></li>
                            <li class="divider"></li>
                            <li><a href="/logout/">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        {% block content %}{% endblock %}
    </div>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/ripples.min.js"></script>
    <script src="/static/js/material.min.js"></script>
    <script>

        $(document).ready(function() {
            // This command is used to initialize some elements and make them work properly
            $.material.init();
        });

        document.getElementById("submit").onclick = function() {
            var search_query = document.getElementById('searchfield').value;
            $(location).attr('href', '/reports/' + '?search=' + search_query);
        };

        $("#searchfield").bind("keypress", {}, keypressInBox);
        function keypressInBox(e) {
            var code = (e.keyCode ? e.keyCode : e.which);
            if (code == 13) { //Enter keycode
                e.preventDefault();
                var search_query = document.getElementById('searchfield').value;
                $(location).attr('href', '/reports/' + '?search=' + search_query);
            }
        }
    </script>

    <script>
        {% block bottomscripts %}{% endblock %}
    </script>

</body>

</html>

templates/navbar.html
    <div class="pull-right">
        Welcome, {{ user.username }} {% if user.is_staff %}[ <a href="{% url 'admin:index' %}">Admin</a> ] {% endif %}[ <a href="{% url 'logout' %}">Logout</a> ]
    </div>
    
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentaion" {% if active_tab == 'new_task' %} class="active"{% endif %}>
            <a href="{% if active_tab == 'new_task' %}#{% else %}{% url 'interface:new_task' %}{% endif %}">
                <span class="glyphicon glyphicon-screenshot" aria-hidden="true"></span> New task
            </a>
        </li>
        <li role="presentaion" {% if active_tab == 'reports' %} class="active"{% endif %}>
            <a href="{% if active_tab == 'reports' %}#{% else %}{% url 'interface:reports' %}{% endif %}">
                <span class="glyphicon glyphicon-file" aria-hidden="true"></span> Reports
            </a>
        </li>
        <li role="presentaion" {% if active_tab == 'search' %} class="active"{% endif %}>
            <a href="{% if active_tab == 'search' %}#{% else %}#{% endif %}">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
            </a>
        </li>
    </ul>